function buildListBuilder()
    local listBuilder = {}
    listBuilder.modelTemplateGUID = "ba9920"
    listBuilder.redZoneGUID = "2c09a9"
    listBuilder.blueZoneGUID = "818608"

    listBuilder.redDeckMountGUID = "eb2d78"
    listBuilder.blueDeckMountGUID = "0c1c93"

    listBuilder.redDeckZoneGUID = "99d398"
    listBuilder.blueDeckZoneGUID = "4541f9"

    listBuilder.redCounterGUID = "5c7de3"
    listBuilder.blueCounterGUID = "55da62"

    listBuilder.commandCardsGUID = "4ee41a"

    listBuilder.dataDisk = {}
    listBuilder.dataDisk.guid = "66f23c"

    listBuilder.redDataDiskZone = "ccdc98"
    listBuilder.blueDataDiskZone = "cd7b3b"

    listBuilder.deckBuilderPos = {}

    listBuilder.deckBuilderPos.red = {-35.11, 0.95, -30.45}
    listBuilder.deckBuilderPos.blue = {-35.11, 0.95, 30.45}

    listBuilder.deckBuilderMesh = "http://cloud-3.steamusercontent.com/ugc/786360308354566451/1A3E2F61E3596E35D3FFA10660B8C63D5BE010E1/"
    listBuilder.deckBuilderDiffuse = "http://cloud-3.steamusercontent.com/ugc/786360308354566564/58E3DBF4523A099C371DA8A674AE9DB1932B4006/"
    listBuilder.deckBuilderGUID = "082f27"

    listBuilder.redTemplatePos = {}
    listBuilder.redTemplatePos[1] = {x = -23.57,y= 1,z=-30}
    listBuilder.redTemplatePos[2] = {x =-16.60,y= 1,z=-30}
    listBuilder.redTemplatePos[3] = {x =-9.60,y= 1,z=-30}
    listBuilder.redTemplatePos[4] = {x =-2.63,y= 1,z=-30}
    listBuilder.redTemplatePos[5] = {x =4.38,y= 1,z=-30}
    listBuilder.redTemplatePos[6] = {x =11.38,y= 1,z=-30}
    listBuilder.redTemplatePos[7] = {x =18.35,y= 1,z=-30}
    listBuilder.redTemplatePos[8] = {x =25.07,y= 1,z=-30}
    listBuilder.redTemplatePos[9] = {x =32.36,y= 1,z=-30}
    listBuilder.redTemplatePos[10] = {x =39.37,y= 1,z=-30}

    listBuilder.redTemplatePos[11] = {x = -23.57,y= 1,z= -39}
    listBuilder.redTemplatePos[12] = {x =-16.60,y= 1,z= -39}
    listBuilder.redTemplatePos[13] = {x =-9.60,y= 1,z= -39}
    listBuilder.redTemplatePos[14] = {x =-2.63,y= 1,z= -39}
    listBuilder.redTemplatePos[15] = {x =4.38,y= 1,z= -39}
    listBuilder.redTemplatePos[16] = {x =11.38,y= 1,z= -39}
    listBuilder.redTemplatePos[17] = {x =18.35,y= 1,z= -39}
    listBuilder.redTemplatePos[18] = {x =25.07,y= 1,z= -39}
    listBuilder.redTemplatePos[19] = {x =32.36,y= 1,z= -39}
    listBuilder.redTemplatePos[20] = {x =39.37,y= 1,z= -39}



    listBuilder.blueTemplatePos = {}
    listBuilder.blueTemplatePos[1] = {x=39.37,y= 1,z=30}
    listBuilder.blueTemplatePos[2] = {x=32.36,y= 1,z=30}
    listBuilder.blueTemplatePos[3] = {x=25.07,y= 1,z=30}
    listBuilder.blueTemplatePos[4] = {x=18.35,y= 1,z=30}
    listBuilder.blueTemplatePos[5] = {x=11.38,y= 1,z=30}
    listBuilder.blueTemplatePos[6] = {x=4.38,y= 1,z=30}
    listBuilder.blueTemplatePos[7] = {x=-2.63,y= 1,z=30}
    listBuilder.blueTemplatePos[8] = {x=-9.60,y= 1,z=30}
    listBuilder.blueTemplatePos[9] = {x=-16.60,y= 1,z=30}
    listBuilder.blueTemplatePos[10] = {x=-23.57,y= 1,z=30}

    listBuilder.blueTemplatePos[11] = {x=39.37,y= 1,z=39}
    listBuilder.blueTemplatePos[12] = {x=32.36,y= 1,z=39}
    listBuilder.blueTemplatePos[13] = {x=25.07,y= 1,z=39}
    listBuilder.blueTemplatePos[14] = {x=18.35,y= 1,z=39}
    listBuilder.blueTemplatePos[15] = {x=11.38,y= 1,z=39}
    listBuilder.blueTemplatePos[16] = {x=4.38,y= 1,z=39}
    listBuilder.blueTemplatePos[17] = {x=-2.63,y= 1,z=39}
    listBuilder.blueTemplatePos[18] = {x=-9.60,y= 1,z=39}
    listBuilder.blueTemplatePos[19] = {x=-16.60,y= 1,z=39}
    listBuilder.blueTemplatePos[20] = {x=-23.57,y= 1,z=39}

    listBuilder.miniSpawnPos = {}
    listBuilder.miniSpawnPos[1] = {c = 5.32, q = -90}
    listBuilder.miniSpawnPos[2] = {q = 74.097447395813,  c = -5.5109073663055}
    listBuilder.miniSpawnPos[3] = {q = 83.470464001153, c = -6.6833524521754}
    listBuilder.miniSpawnPos[4] = {q = -83.460700769998, c = 6.6734174153878}
    listBuilder.miniSpawnPos[5] = {q = -73.826845678316, c = 5.5288063811279}
    listBuilder.miniSpawnPos[6] = {q = -78.799202212116, c = 4.1184463089859}
    listBuilder.miniSpawnPos[7] = {q = 79.544342439695, c = -4.0777076893764}
    listBuilder.miniSpawnPos[8] = {c = 7.9, q = -90}

    listBuilder.handPos = {}
    listBuilder.handPos.red = {}
    listBuilder.handPos.red.pos = {8.50, 4.0, -58}
    listBuilder.handPos.red.rot = {0,180,0}
    listBuilder.handPos.blue = {}
    listBuilder.handPos.blue.pos = {8.50, 4.0, 58}
    listBuilder.handPos.blue.rot = {0,0,0}

    listBuilder.tokenModelGUID = "a57c41"
    modelToken = getObjectFromGUID(listBuilder.tokenModelGUID)
    listBuilder.tokenScript = modelToken.getLuaScript()

    listBuilder.modelMiniGUID = "99f1c8"
    modelMini = getObjectFromGUID(listBuilder.modelMiniGUID)
    listBuilder.modelMiniScript = modelMini.getLuaScript()


    listBuilder.commandCards = {}
    -- IMPERIAL
    listBuilder.commandCards["general veers master tactician"] = {
        varName = "generalVeers",
        cards = {"Maximum Firepower","Evasive Maneuvers","Imperial Discipline"}

    }
    listBuilder.commandCards["imperial officer ruthless commander"] = {
        varName = "imperialOfficer"
    }
    listBuilder.commandCards["darth vader dark lord of the sith"] = {
        varName = "darthVader",
        cards = {"Implacable","New Ways to Motivate Them","Master of Evil"},
        cards2 = {"Vader's Might","Fear and Dead Men","Darkness Descends"}
    }
    listBuilder.commandCards["darth vader the emperor's apprentice"] = {
        varName = "darthVaderTheEmperorsApprentice",
        cards = {"Implacable","New Ways to Motivate Them","Master of Evil"},
        cards2 = {"Vaders Might","Fear and Dead Men","Darkness Descends"}
    }
    listBuilder.commandCards["emperor palpatine ruler of the galactic empire"] = {
        varName = "emperorPalpatine",
        cards = {"And Now... You Will Die", "Give in to Your Anger", "An Entire Legion"}
    }
    listBuilder.commandCards["director orson krennic architect of terror"] = {
        varName = "directorOrsonKrennic",
        cards = {"Voracious Ambition", "Deploy the Garrison", "Annihilation Looms"}
    }
    listBuilder.commandCards["iden versio inferno squad leader"] = {
        varName = "idenVersio",
        cards = {"Pulse Scan", "Concussive Blast", "Tactical Strike"},
        cards2 = {"Ambush", "Incapacitate", "Assault"}
    }
    listBuilder.commandCards["agent kallus hunter of spectres"] = {
        varName = "agentKallus",
        cards = {"Face Me!", "ISB Investigation", "Ruthless Tactics"}
    }
    listBuilder.commandCards["boba fett infamous bounty hunter"] = {
        varName = "bobaFett",
        cards = {"Whipcord Launcher", "ZX Flame Projector", "Z-6 Jetpack Rocket"}
    }
    listBuilder.commandCards["bossk trandoshan terror"] = {
        varName = "bossk",
        cards = {"Merciless Munitions", "Reptilian Rampage", "Lying in Wait"}
    }

    -- REBEL
    listBuilder.commandCards["luke skywalker hero of the rebellion"] = {
        varName = "lukeSkywalker",
        cards = {"Son of Skywalker", "My Ally Is the Force", "Return of the Jedi"},
        cards2 = {"You Serve Your Master Well", "Full of Surprises", "I am a Jedi"}
    }
    listBuilder.commandCards["luke skywalker jedi knight"] = {
        varName = "lukeSkywalkerJediKnight",
        cards = {"Son of Skywalker", "My Ally Is the Force", "Return of the Jedi"},
        cards2 = {"You Serve Your Master Well", "Full of Surprises", "I am a Jedi"}
    }
    listBuilder.commandCards["leia organa fearless and inventive"] = {
        varName = "leiaOrgana",
        cards = {"Coordinated Bombardment","No Time for Sorrows","Somebody Has to Save Our Skins"}
    }
    listBuilder.commandCards["han solo unorthodox general"] = {
        varName = "hanSolo",
        cards = {"Sorry About the Mess","Reckless Diversion","Change of Plans"}
    }
    listBuilder.commandCards["jyn erso stardust"] = {
        varName = "jynErso",
        cards = {"Rebellious","Trust Goes Both Ways","Complete the Mission"}
    }
    listBuilder.commandCards["cassian andor capable intelligence agent"] = {
        varName = "cassianAndor",
        cards = {"Crack Shot","Last Stand","Volunteer Mission"}
    }
    listBuilder.commandCards["k-2so sardonic security droid"] = {
        varName = "k2so",
        cards = {"Ambush", "Push", "Sacrifice"}
    }
    listBuilder.commandCards["chewbacca walking carpet"] = {
        varName = "chewbacca",
        cards = {"Common Cause","Brains and Brawn","Notorious Scoundrels"}
    }
    listBuilder.commandCards["sabine wren explosive artist"] = {
        varName = "sabineWren",
        cards = {"Explosions!","Symbol of Rebellion","Legacy of Mandalore"}
    }
    listBuilder.commandCards["r2-d2 hero of a thousand devices"] = {
        varName = "r2d2",
        cards = {"Blast Off!", "Impromptu Immolation", "Smoke Screen"}
    }
    listBuilder.commandCards["c3po human-cyborg relations"] = {
        varName = "c3po",
        cards = {"Ambush", "Push", "Assault"}
    }
    listBuilder.commandCards["rebel officer resolute commander"] = {
        varName = "rebelOfficer"
    }
    listBuilder.commandCards["lando calrissian smooth operator"] = {
        varName = "landoCalrissian",
        cards = {"Idiots Array", "Ace Up His Sleeve", "All In"}
    }
    -- SEPARATIST
    listBuilder.commandCards["general grievous sinister cyborg"] = {
        varName = "generalGrievous",
        cards = {"Trained in Your Jedi Arts","Supreme Commander","Crush Them!"}
    }
    listBuilder.commandCards["count dooku darth tyranus"] = {
        varName = "countDooku",
        cards = {"Fear, Suprise, Intimidation","Double the Fall","You Disappoint Me"}
    }
    listBuilder.commandCards["cad bane needs no introduction"] = {
        varName = "cadBane",
        cards = {"I'm Your Worst Nightmare","I'm In Control","I Make The Rules Now"}
    }
    listBuilder.commandCards["maul impatient apprentice"] = {
      varName = "maul",
      cards = {"Duel Of The Fates","The Phantom Menace","At Last"}
    }
    listBuilder.commandCards["t-series tactical droid programmed for strategy"] = {
    varName = "tSeriesTacticalDroid"
    }
    -- REPUBLIC
    listBuilder.commandCards["obi-wan kenobi civilized warrior"] = {
        varName = "obiWanKenobi",
        cards = {"Hello There!","Knowledge and Defense","General Kenobi"}
    }
    listBuilder.commandCards["clone captain rex honorable soldier"] = {
        varName = "cloneCaptainRex",
        cards = {"Call Me Captain","Take That, Clankers!","Were Not Programmed"}
    }
    listBuilder.commandCards["anakin skywalker the chosen one"] = {
      varName = "anakinSkywalker",
      cards = {"This Is Where The Fun Begins","You Underestimate My Power","Hero Of The Clone Wars"}
  }
    listBuilder.commandCards["r2-d2 independent astromech"] = {
        varName = "republicR2d2",
        cards = {"Blast Off!", "Impromptu Immolation", "Smoke Screen"}
    }
    listBuilder.commandCards["c3po made to suffer"] = {
        varName = "republicC3po",
        cards = {"Ambush", "Push", "Assault"}
    }
    listBuilder.commandCards["padme amidala spirited senator"] = {
        varName = "padme",
        cards = {"Our Fate Is In Your Hands", "Aggressive Negotiations", "Diplomatic Cover"}
    }
    listBuilder.commandCards["clone commander trained for leadership"] = {
        varName = "cloneCommander"
    }
    -- NEUTRAL
    listBuilder.commandCards.neutral = {
        varName = "neutral",
        cards = {"Ambush", "Push", "Assault"}
    }
    listBuilder.commandCards.neutralAltArt = {
        varName = "neutral",
        cards = {"Ambush Alt Art", "Push Alt Art", "Assault Alt Art"}
    }
    listBuilder.commandCards.neutralImperial = {
        varName = "neutralImperial",
        cards = {"Covert Observation", "Pinned Down", "Coordinated Fire"}
    }
    listBuilder.commandCards.neutralRebel = {
        varName = "neutralRebel",
        cards = {"Sabotaged Communications", "Turning the Tide", "Covering Fire"}
    }
    listBuilder.commandCards.neutralSeparatist = {
        varName = "neutralSeparatist",
        cards = {"Mechanized Incursion", "Orbital Strike", "Roger, Roger!"}
    }
    listBuilder.commandCards.neutralRepublic = {
        varName = "neutralSeparatist",
        cards = {"Synchronized Offensive", "Air Support", "Attack Of The Clones"}
    }
    return listBuilder
end
