function buildMiniInfo()
  local _BASE_COLLIDERS = {
    small = { "http://cloud-3.steamusercontent.com/ugc/1009315641457429932/1534D6C1AA4F3D5BDA469241B8F0319BE560E7ED/", 1.06299},
    medium = { "http://cloud-3.steamusercontent.com/ugc/1009315641457670521/DAD6653F422046BD6BC4360FE18C96927D5F4C44/", 1.9685},
    large = { "http://cloud-3.steamusercontent.com/ugc/1009315641457670155/6727179496A9F397E953AAA3268C6CC6444598DF/", 2.75591},
    huge = { "http://cloud-3.steamusercontent.com/ugc/1009315641457669798/3B337900892D839BDBC3EBF2A5CC9EC87DDBFED1/", 3.93701},
    epic = { "http://cloud-3.steamusercontent.com/ugc/1009315641457669292/A7F6F75580BF1DFAA23E621875A761FB8B9EF2BC/", 5.90551},
    long = { "http://cloud-3.steamusercontent.com/ugc/963116666702885485/70F17B3327115A379D06F81C6F47F76470D7B826/", 6.88976}
  }
  local miniInfo = {}
  miniInfo.lukeSkywalker = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540537100371/0B15B2810ABEBE5429E4A24852D96BAC2DC28BF7/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540537079134/11A17263AD81DC9D4271B7C6BD809B69141DCB61/",
      name = "Luke Skywalker"
  }
  miniInfo.lukeSkywalkerJediKnight = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/777357228030156264/12F93F60CC26F1FDC2B577D4014787B7CAFBF9A1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/777357228030156398/F811CAE962A0BFE369544C0A96C251F5BF198B3A/",
      name = "Luke Skywalker Jedi Knight"
  }
  miniInfo.leiaOrgana = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540537137572/2AC01B05AF1576F49C3156EDB614E2C1804C2A42/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540537137853/F8E5FE7B221E9115B36E22C14E5707B7CFA6CFC3/",
      name = "Leia Organa"
  }
  miniInfo.hanSolo = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540669649/C440F429AB1182944D329D0C16C3402DB731CA87/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540669835/B4E395AA781518EAC4FBFFCB27BAA646201F411C/",
      name = "Han Solo"
  }
  miniInfo.jynErso = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475778/55B558E631655D0430BAF76E71C93899AAECA7A1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305475871/06400240648CC39F933BE504C74DA9BEF4D006C4/",
      name = "Jyn Erso"
  }
  miniInfo.cassianAndor = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/773996263556990389/C38E9CAD7E5BA5496E1A211CA799E9ACBAC51D00/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770611701143191344/5CAA4F0CE9A3FBE89A81560221ADCDDB5A801CC3/",
      name = "Cassian Andor"
  }
  miniInfo.landoCalrissian = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1666859827674318376/E0A03ACDC6D2F607B8CC0C406AE196A9DB5347B7/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1666859827674318640/6674121C184DF4BBD67EAB0DAA75F6B41A93669A/",
      name = "Lando Calrissian"
  }
  miniInfo.k2so = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/773996263557000439/C9EA2A27264C73E42C016FE26E665CBB75F8E7DE/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770611701143471855/26BE70BB475D8B61122C8954CCA2EC79C1ED4C25/",
      name = "K-2SO"
  }
  miniInfo.chewbacca = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540669973/90DD9EA44756CCF9B2473302DC644F3AEEED07B4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670117/5AA04499FC8CC467864F9F335601E6335C03326D/",
      name = "Chewbacca"
  }
  miniInfo.sabineWren = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/948474323838790939/3E9EB4AAF653CD476FF3D90EA82072EDC2D4AC66/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/948474323838791034/38CDAF985C2DC983942183E1DFD3ACBC33D8E40E/",
      name = "Sabine Wren"
  }
  miniInfo.r2d2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/776232727456806966/EFBA4A71BFE748A2868C14B82DA3A7B0D559874A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/777357228032306302/F5CA6FC54A8625E261F123D73792DE36D74E1686/",
      name = "R2-D2"
  }
  miniInfo.c3po = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/776232727456807069/DE7E32B39455DB5111769436FD0C5BFDA3841268/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/777357228032306506/D60CB8A1159723917EF1831D4042318A67458A7A/",
      name = "C-3PO"
  }
  miniInfo.rebelOfficer = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862726770/62FECAB3FED284E098751CC3BBC70C4CFF828A58/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862727097/DE589901F66E4079D82BA2C819672F622A5D7240/",
      name = "Rebel Officer"
  }
  miniInfo.rebelOfficerLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862726770/62FECAB3FED284E098751CC3BBC70C4CFF828A58/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862727097/DE589901F66E4079D82BA2C819672F622A5D7240/",
      name = "Rebel Officer",
      leader = true
  }

  miniInfo.rebelTrooper1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862752262/41BD6AB8B17AB7449226A3D80EF186EB8ABA3952/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862750426/2563904D7561144EE85EBCD3E07D68F48D8DD034/",
      name = "Rebel Trooper"
  }
  miniInfo.rebelTrooper2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862764799/98CBD8B4DD0C08CFA01A8E6C8B5A70A137804EAB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862750426/2563904D7561144EE85EBCD3E07D68F48D8DD034/",
      name = "Rebel Trooper"
  }
  miniInfo.rebelTrooper3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862755846/CD522BCA5D6E918E13A3FF593D7212FF4B0E79CA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862750426/2563904D7561144EE85EBCD3E07D68F48D8DD034/",
      name = "Rebel Trooper"
  }
  miniInfo.rebelTrooper4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862761532/2FB3D83FC2BD077F4ADE619382382B9A59CD0ABE/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862750426/2563904D7561144EE85EBCD3E07D68F48D8DD034/",
      name = "Rebel Trooper"
  }
  miniInfo.rebelTrooperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862746147/3F3A21962C4AC0DA0445024688BF580A144D3825/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670236/6257E7A3CE86803490A8A0FAC7F81C281D700F52/",
      name = "Rebel Trooper Leader",
      altModelInfo = miniInfo.rebelTrooper4
  }
  miniInfo.z6Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862734756/1F48FA301357905B28DA35A03658DFA39154DBFE/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862736228/22D1A1ACC79493FE82165CC95A5E23170A4FBC5B/",
      name = "Z-6 Trooper"
  }
  miniInfo.mpl57IonTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540670338/28625FDF1F56EF08F0DB236C4ECFF67A54083B2B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862750426/2563904D7561144EE85EBCD3E07D68F48D8DD034/",
      name = "MPL-57 Ion Trooper"
  }
  miniInfo.fleetTroopers1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540670667/CB316B23D59F28C5EF22E94A43280D49DFFDD6AC/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670760/47DF3E87B3F71E8EA42A89ECFE96E4FB3990D7ED/",
      name = "Fleet Trooper"
  }
  miniInfo.fleetTroopers2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540671182/A605D9D0DB356DC71473F5C9DF27DE1CADB4F320/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540671278/9B94D359A61113F72EEB0435D70A1291431D737A/",
      name = "Fleet Trooper"
  }
  miniInfo.fleetTroopers3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540670978/0642E99CB4E8CABA1AA10389F2387A1C70D9322D/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670760/47DF3E87B3F71E8EA42A89ECFE96E4FB3990D7ED/",
      name = "Fleet Trooper"
  }
  miniInfo.fleetTroopers4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540670863/20FE73C6E9F8468BD468C820C88EAB9F697EC33E/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670760/47DF3E87B3F71E8EA42A89ECFE96E4FB3990D7ED/",
      name = "Fleet Trooper"
  }
  miniInfo.fleetTroopersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540670464/96FB3825C890968C09B07A2E0E227886D2CC768C/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670556/9B759F6F1A8B7C11AE5F2908208CBA9EF99ECE2C/",
      name = "Fleet Trooper Leader",
      altModelInfo = miniInfo.fleetTroopers4
  }
  miniInfo.scatterGunTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540671094/4A4BCE6286ACB413B661F827BB00B920617F3E91/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540670760/47DF3E87B3F71E8EA42A89ECFE96E4FB3990D7ED/",
      name = "Scatter Gun Trooper"
  }
  miniInfo.mpl57BarrageTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540540671382/63267B140C2A619525B99FD943DF2421F75B9130/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540540671503/D8BCEE815B07EA7074085CF1F43AF8041DEC8981/",
      name = "MPL-57 Barrage Trooper"
  }
  miniInfo.medicalDroid21B = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594268997/6248E4CAF3E978154106E7095E6984DCE6677CCA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594282950/7A9A3E5518394273A507A64CCF7425A2E7EFC29B/",
      name = "2-1B Medical Droid"
  }
  miniInfo.rebelCommsTechnician = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594474909/F8F049D7F88171ADBA83AF3EAF819495053C2873/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594268734/CF3C536F7B068020A99C5E3EE11CA9C54438E250/",
      name = "Rebel Comms Technician"
  }
  miniInfo.r5AstromechDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594428341/4AC5A309D701979A4B3E94725BC1E8745C598BCE/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594267684/F84F03E4A52F50EF5255A464FF85083CF4FB3D26/",
      name = "R5 Astromech Droid"
  }
  miniInfo.rebelTrooperSpecialist = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173464719285/839B79B3594F31585EB38763EDF43AD32E46F37F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173464692456/FD09533718942CE5B08526B2CD1A00D5D38CB734/",
      name = "Rebel Trooper Specialist"
  }
  miniInfo.sx21Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173464725382/9DADA91B7A5BE8DEEC1BDE838B3140A350D661A4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173464726852/2ABBCC6938695708489FB87C27C6B7481A1D294A/",
      name = "SX-21 Trooper"
  }
  miniInfo.dlt20ATrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173464888456/63604C016242E6F545F139BC46515E0A894EC6B2/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173464889098/17A7BE90F158B80F88518F92EA4D211F16E14003/",
      name = "DLT-20A Trooper"
  }
  miniInfo.rebelTrooperCaptain = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173464670173/ECC18FB91315A55181F38A6899122E005460C688/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173464683373/FE0A29CF1A46E7F97FEAE0C9FD665AB192A8D9A8/",
      name = "Rebel Trooper Captain",
      leader = true
  }
  miniInfo.rebelVeteransLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499192015/F194EFE217778158ED30DFD40EFC1F70BEC01772/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "Rebel Veterans Leader",
      altModelInfo = miniInfo.rebelVeteransLeader
  }
  miniInfo.rebelVeterans1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499192232/D15615AF2A0F4F4887E9BD3DFFA141C8ACCCEC78/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "Rebel Veteran"
  }
  miniInfo.rebelVeterans2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499192402/4D1858AA566FEEE91774E40B10C233AAD8C381D5/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "Rebel Veteran"
  }
  miniInfo.rebelVeterans3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499192498/BF583EA43B457E816CDE323C172B2F4558B7A8BD/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "Rebel Veteran"
  }
  miniInfo.rebelVeterans4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499192589/466305BFF474DBAB11F58FA13B3F4ACC9BB7127C/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "Rebel Veteran"
  }
  miniInfo.cm093Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702687947/DCC60167A78C152DDAE932E699D7C70C5629008B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499192135/526538CE10AC6856578996BE6B8AB7263D32D5C7/",
      name = "CM-0/93 Trooper"
  }
  miniInfo.markIIMediumBlasterTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688462/6B35D0B4E18CB7D0081825BEDC6E6C4AE45AA329/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702688570/1827E8E24FE65F309AF936EF35D07CC2149CD95E/",
      name = "Mark II Medium Blaster Trooper"
  }
  miniInfo.rebelCommandosLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173156/D637683F992DD0C4488252BE266EEEA1F26006B0/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541172655/B10522A40482843AF69A3F321BD091B0ECF52C6B/",
      name = "Rebel Commandos Leader"
  }
  miniInfo.rebelCommandos1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541172497/B3E1593143504101920CC6419BE7C2EAEF52993F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541188141/6E23E29BB42963B94A0B7DFE01C4C49D776D9657/",
      name = "Rebel Commandos"
  }
  miniInfo.rebelCommandos2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173253/155BAA01BA51A8EB524DD434A3C512D8C0B3A04B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541172655/B10522A40482843AF69A3F321BD091B0ECF52C6B/",
      name = "Rebel Commandos"
  }
  miniInfo.rebelCommandos3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173354/3483C6FB73C66481BC6CCC398BAB8E796F7EC076/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541188141/6E23E29BB42963B94A0B7DFE01C4C49D776D9657/",
      name = "Rebel Commandos"
  }
  miniInfo.rebelCommandos4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173710/DAD1A2BE9F1D9C74C10D975D5AD5FDA05566C100/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541172655/B10522A40482843AF69A3F321BD091B0ECF52C6B/",
      name = "Rebel Commandos"
  }
  miniInfo.dh447Sniper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862776611/B8222AA4A3B680E969DC106C8A281D11845994EB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862776974/21649563BC0CB84E12C0B249C720919F528596D3/",
      name = "DH-447 Sniper"
  }
  miniInfo.dh447SniperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780862776611/B8222AA4A3B680E969DC106C8A281D11845994EB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780862776974/21649563BC0CB84E12C0B249C720919F528596D3/",
      name = "DH-447 Sniper",
      leader = true
  }
  miniInfo.protonChargeSaboteur = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173465/8193FD1F0862270CD23BA9243679840BE6324DC6/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541173570/3C100E92F0DEDEF117D3A0392D3271951BC90DD0/",
      name = "Proton Charge Saboteur"
  }
  miniInfo.protonChargeSaboteurLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173465/8193FD1F0862270CD23BA9243679840BE6324DC6/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541173570/3C100E92F0DEDEF117D3A0392D3271951BC90DD0/",
      name = "Proton Charge Saboteur",
      leader = true
  }
  miniInfo.wookieeWarriorsLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541173937/5179F4315AD6B0839454E1934E794A7F006C7813/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541174467/18352D89A219B89F6C869D89B9EDE22822F7F950/",
      name = "Wookiee Warriors Leader"
  }
  miniInfo.wookieeWarriors1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541174158/677BF72C323CFF2314C174393AFA361C398C5519/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541174034/90C4A124BB82CCE0B5E38E13860ED49BB9A4973B/",
      name = "Wookiee Warrior"
  }
  miniInfo.wookieeWarriors2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541174304/9053CDD2798CEA905F8486498D0104B6ACA2F078/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541174467/18352D89A219B89F6C869D89B9EDE22822F7F950/",
      name = "Wookiee Warrior"
  }
  miniInfo.bowcasterWookiee = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541174665/9E1AA98159F76E271185345E9D347D7453C05D4B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541174034/90C4A124BB82CCE0B5E38E13860ED49BB9A4973B/",
      name = "Bowcaster Wookiee"
  }
  miniInfo.rebelPathfindersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475193/3C613417B99B185BBAEC7A4C66AAE10E8FD6F8D5/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305475310/FF2A55C2559DA2CA2108EE6D7E5605774EF1B04D/",
      name = "Rebel Pathfinders Leader"
  }
  miniInfo.rebelPathfinders1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475558/EE0863D9DE3C9D35C486B7273E1D555BB1F09566/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305475310/FF2A55C2559DA2CA2108EE6D7E5605774EF1B04D/",
      name = "Rebel Pathfinders"
  }
  miniInfo.rebelPathfinders2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475456/26BF332D69FD5B08D677EBDB91948820E03690DB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305475310/FF2A55C2559DA2CA2108EE6D7E5605774EF1B04D/",
      name = "Rebel Pathfinders"
  }
  miniInfo.rebelPathfinders3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475667/B5CC42E1CAB9059DEE4B1237222CF0FE3BB6B838/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305475310/FF2A55C2559DA2CA2108EE6D7E5605774EF1B04D/",
      name = "Rebel Pathfinders"
  }
  miniInfo.pao = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/993513208355174746/6F5A50CE6D4E23C6278AE868FD359A49E1C80179/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/993513208355174858/CCC2B3862F1FEB611B03317594F6F0E761750C70/",
      name = "Pao",
      leader = true
  }
  miniInfo.bistan = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/993513208355174951/467D917BF6BCABCC9F6DD17F5DEDB43A11DEA9A7/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/993513208355175183/AD143EC79EC2BA3E7B93B114CC8AFEAAD322D806/",
      name = "Bistan"
  }
  miniInfo.mandalorianResistanceLeader = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696350886421665/441B37D17213CA1B82174A8988ED23AA2D59336E/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696350886421832/BBE3592A7496E444E116271913178A8ED41F5323/",
    name = "Mandalorian Resistance Leader"
  }
  miniInfo.mandalorianResistance1 = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696515357880094/FFFBDA79DE3B6192926EFCDFC257708C2A360562/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696515357880292/78883B5B08CCDC0B7BC4EF36D45DAB06E9057FEB/",
    name = "Mandalorian Resistance"
  }
  miniInfo.mandalorianResistance2 = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696350886396178/07FB37CA0A11552BEF96C3DCA10AF232C65AF7B6/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696350886396372/35E5047903DC30F882B40719809ECF90DBC65A5A/",
    name = "Mandalorian Resistance"
  }
  miniInfo.clanWren1 = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696515357880886/06542D3BD6F03DC43D9E675680F86F2964B210F9/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696515357880292/78883B5B08CCDC0B7BC4EF36D45DAB06E9057FEB/",
    name = "Clan Wren"
  }
  miniInfo.beskadDuelist = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696515357841451/50164A1C84E6D119BC45BDD31C8209ED7D9A0F29/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696515357841757/1DC29C81D9DFCB2FB7D8A3B2EA2F2ABD3F416396/",
    name = "Beskad Duelist"
  }
  miniInfo.ursaWren = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696515357881561/B365369415AE0FB6A96E69817D76D9BAD1366038/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696515357880292/78883B5B08CCDC0B7BC4EF36D45DAB06E9057FEB/",
    name = "Ursa Wren",
    leader = true
  }
  miniInfo.tristanWren = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1021696350886429750/5D62ADB1200B1AD16A0349AF87E757F40E720115/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1021696350886427771/60D6CA1D97D822A2222E4FAF614931265B7B0AF2/",
    name = "Tristan Wren"
  }

  miniInfo.atrt = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541266463/014ECD21C93F864E1C1DFD104A365DFC555EBAF8/",
      collider = _BASE_COLLIDERS.large,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541267239/D9891291A896CC024383C024B20C5ACF87EC8A18/",
      name = "AT-RT"
  }
  miniInfo.tauntaunRidersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499191489/E91DEB380842511B21284A125A505B6C71D18474/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499191676/8E19A176FF0B3D2923F8F3D6DEA80D389F77CB27/",
      name = "Tauntaun Rider Leader"
  }
  miniInfo.tauntaunRiders1= {
      mesh = "http://cloud-3.steamusercontent.com/ugc/788608699499191881/3DBB7DF0943F0D25484DE34581411825BA566F8A/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/788608699499191676/8E19A176FF0B3D2923F8F3D6DEA80D389F77CB27/",
      name = "Tauntaun Rider"
  }
  miniInfo.fdLaserCannonTeam = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541267781/BE163E2112B28E8C7C5E536B037D3115103F9642/",
      collider = _BASE_COLLIDERS.huge,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541269701/797EACA86E0FB799D16DC8FE907A70C4B976C5EE/",
      name = "1.4 FD Laser Cannon Team"
  }
  miniInfo.airSpeeder = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/999141806429331055/047818ABA85804B98787BC67BEF12D24EC8F8ADB/",
      collider = _BASE_COLLIDERS.huge,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541315963/DD72FAD5F49D303A83A4463B0D3796E3A8FD5BE8/",
      name = "T-47 Airspeeder"
  }
  miniInfo.x34Landspeeder = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594267188/9FA2B8A42C94B6E3683F1B753CEBA14FC3258592/",
      collider = _BASE_COLLIDERS.huge,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594267308/582E5F56A65FE6CD486BCBABB510CAE4B4DF6C8C/",
      name = "X-34 Landspeeder"
  }
  miniInfo.aa5SpeederTruck = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1803107668954610246/3C643CD6824D7380C1DE15EADAA53243607E8019/",
    name = "A-A5 Speeder Truck"
  }

  miniInfo.darthVader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541323740/BF58AB674CB7D638333F1B04A7C9A5B9D7DBF0E4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541324289/B37D84D512722740E8310629C3E7BFC45AF0FBC9/",
      name = "Darth Vader"
  }
  miniInfo.darthVaderTheEmperorsApprentice = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/777357228030156593/FEBA127ECDF2917EA8F8066BBB10BADA7D365D3E/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541324289/B37D84D512722740E8310629C3E7BFC45AF0FBC9//",
      name = "Darth Vader The Emperors Apprentice"
  }
  miniInfo.generalVeers = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541565411/F5F84397A9353DAD3D913F34E49812C1C895DA65/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541565593/F948637FEE70F52681A5A3C49C0E00EF25471AC1/",
      name = "General Veers"
  }
  miniInfo.emperorPalpatine = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541565714/71E1936EB657F4BC1074EB740BC9AA0531A130AC/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541565804/0EB3EBFD318678DBE5B7C83B39A31DC8AB3376B6/",
      name = "Emperor Palpatine"
  }
  miniInfo.directorOrsonKrennic = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305476013/77069645EC03E0F1C1DB10C2CE7EA85917E45404/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305476130/772EEBD3EC49A7271C1C7647F817C51ED23DE3B2/",
      name = "Director Orson Krennic"
  }
  miniInfo.idenVersio = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/773996263557021593/68887AFFBF8F1A2472A80F6514CD617A54A1D705/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770611889400014191/9442AAB074AB2204C7A5CD8843037C71CFC44540/",
      name = "Iden Versio"
  }
  miniInfo.id10 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/773996263557020821/1E2319EBFD85D7748450F40689A1315696052EFC/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770611889399999868/37F150131345FF1F47592A96239395A583AAE5EA/",
      name = "ID10"
  }
  miniInfo.agentKallus = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1666859827673303054/77A1D7624FA565991825B19513DBE6B70BD4F93C/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1666859827673291479/CA1D69C65D0F6FD2AE838BFFA3FD85A48CCBFB6C/",
      name = "Agent Kallus"
  }
  miniInfo.imperialOfficer = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541565898/F06AB6731446249164D34ACA208E4FAE70C6FE00/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541566011/A7A84EBF79DA5E1D5BCE71E863FC16EC40937F6F/",
      name = "Imperial Officer"
  }
  miniInfo.imperialOfficerLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541565898/F06AB6731446249164D34ACA208E4FAE70C6FE00/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541566011/A7A84EBF79DA5E1D5BCE71E863FC16EC40937F6F/",
      name = "Imperial Officer",
      leader = true
  }
  miniInfo.bobaFett = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541667697/9BC2C54E14EA265620F3D96553274503245D1681/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541669466/60DFE8F3EC756ECE7E5729D3261EF37CACA587C6/",
      name = "bobaFett"
  }
  miniInfo.bossk = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/948474323838791181/6B9D77B77DF8FD7AFA19342AD687F0E15A2E21B7/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/948474323838791276/ABFCDD8C71D484E6B6050080BB80B79D0DE93178/",
      name = "bossk"
  }

  miniInfo.stormtrooper1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711529/FF076CE02269A8505CB8EFC06749196FFD446391/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper"
  }
  miniInfo.stormtrooper2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711653/C170DF086178164DC66188071D15E9EB36C9A742/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper"
  }
  miniInfo.stormtrooper3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711874/7E06BF6E8E18DD05BBBF10343614B47B8BEE9948/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper"
  }
  miniInfo.stormtrooper4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711777/1E415A2A18F2269B0C63E1C2901E5192DCCFE8CB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper"
  }
  miniInfo.stormtrooperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711094/1DF94C3CDF022814179AFBA6D7521E6196760949/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper Leader",
      altModelInfo = miniInfo.stormtrooper4
  }
  miniInfo.stormtrooperSpecialist = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173464686810/87075FBAEFB7A45C107FEDD41E26ACF148C2592D/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "Stormtrooper Specialist"
  }
  miniInfo.rt97CStormtrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766101851242660925/33331F4DA2AE832C568A49BD24B65D4C1462AF27/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766101851242654975/755ABA199B9C3BEEA1F33AF58FD05D378A67C97F/",
      name = "RT-97C Stormtrooper"
  }
  miniInfo.t21Stormtrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766101851242554815/68F112DE9EC465DA003ECBD26DE129ADD34CD558/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541711313/BBEF6E9A46755A4159DC6222AF0F8302792585D0/",
      name = "T-21 Stormtrooper"
  }
  miniInfo.stormtrooperCaptain = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766101851242555871/B1A38B82950DD8864591296C730D82E0D66BC985/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173464650963/1A63FC0E22280AA3B95488A298270874B7B6CDD2/",
      name = "Stormtrooper Captain",
      leader = true
  }

  miniInfo.snowtrooper1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801837/D52F333945BF667A37E06611977C36186CEFC7B6/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541801215/595165C57A67BF2BD505BE6F0DF8F11AD4EA55D2/",
      name = "Snowtrooper"
  }
  miniInfo.snowtrooper2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801500/728C586E21D0A4EBD8DE54EEF4E097EFEEECE871/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541801215/595165C57A67BF2BD505BE6F0DF8F11AD4EA55D2/",
      name = "Snowtrooper"
  }
  miniInfo.snowtrooper3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801363/743D9E272367ABB1F6296D5EFB6010637C58D5E4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541801215/595165C57A67BF2BD505BE6F0DF8F11AD4EA55D2/",
      name = "Snowtrooper"
  }
  miniInfo.snowtrooper4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801717/EDEA1301FC55A6970D5FBCF0A9F10456E4C2EE40/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541801215/595165C57A67BF2BD505BE6F0DF8F11AD4EA55D2/",
      name = "Snowtrooper"
  }
  miniInfo.snowtrooperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801027/2A5DEE9952A0179FC8448FFA52819B387124ACD7/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541801215/595165C57A67BF2BD505BE6F0DF8F11AD4EA55D2/",
      name = "Snowtrooper Leader",
      altModelInfo = miniInfo.snowtrooper4
  }
  miniInfo.dlt19Stormtrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766101851242465584/D38BBF10F76882CFF4189AB478E9F0691A22298F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766101851242466181/BEF69EF45F1CCEF50CDF7B5CC6E1FE6BDC556310/",
      name = "DLT-19 Stormtrooper"
  }
  miniInfo.t7IonSnowtrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541802160/69A03779E6B67F6F547C2FBD70ACDFC39281387D/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541802252/037749C730FACCA3361B041BCB3C68E7E19DCDF8/",
      name = "T-7 Ion Snowtrooper"
  }
  miniInfo.flametrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541801931/BDE907EBE0BFC0DC4180C76AFEA3F8667013FF3B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541802054/044AD0961CD1485A61AC3B6CB3669FD8AA5A0FEB/",
      name = "Flametrooper"
  }
  miniInfo.hh12Stormtrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541711981/5D8FB39102FEE64DF1802AA71B66666B4E03717F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541712102/C37F3281C89F697024FF1F343B06FB5AC828EA10/",
      name = "HH12 Stormtrooper"
  }
  miniInfo.fx9MedicalDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594268065/7B4874981CECB7BB80D5BC54F60F1939B9A9DAB1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594268174/00246DE6DCE285206330C43B8049B19FFDF5BB41/",
      name = "FX-9 Medical Droid"
  }
  miniInfo.imperialCommsTechnician = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594268417/62CC1D5BCBD1EE294C72781B03AB972B3ED5AD12/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594268526/CA2596C0B2D7DF68D794B2A7880F34B5459F1206/",
      name = "Imperial Comms Technician"
  }
  miniInfo.r4AstromechDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/949599512594492173/DDA1CC3AEEC3D5ADB3B04F35125EE8A6FB7EB93A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/949599512594267919/F44B2C3C810757626C7A4A61DAA7F2BC2BEECFC6/",
      name = "R4 Astromech Droid"
  }
  miniInfo.shoretroopersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688359/642C317FE5C91E4DCC908FEA02A7ED4000B06A9F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687694/C12AAE8B7F487BE4C1545E253AB3C026E0426AA1/",
      name = "Shoretrooper Leader",
      altModelInfo = miniInfo.shoretroopers4
  }
  miniInfo.shoretroopers1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702687570/0D2A602282BAACDCE665EF9D1D65CEA413944083/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687694/C12AAE8B7F487BE4C1545E253AB3C026E0426AA1/",
      name = "Shoretrooper"
  }
  miniInfo.shoretroopers2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688133/C8D721D29D711045A27EEC3868D4B7A111C86F20/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687694/C12AAE8B7F487BE4C1545E253AB3C026E0426AA1/",
      name = "Shoretrooper"
  }
  miniInfo.shoretroopers3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702687282/B02342FDEEE7DDE82DF96EB434B1D033B0A4C899/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687694/C12AAE8B7F487BE4C1545E253AB3C026E0426AA1/",
      name = "Shoretrooper"
  }
  miniInfo.shoretroopers4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688256/B266465186713632AE14D6B4B473AB4E94814685/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687694/C12AAE8B7F487BE4C1545E253AB3C026E0426AA1/",
      name = "Shoretrooper"
  }
  miniInfo.t21BTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702687816/8C17AF1D2344B7E8B1C8D34A0F2228E9ADC2FFAA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702687407/D5B685EA41E9C664F2D16381474B5F08DF9CFAE5/",
      name = "T-21B Trooper"
  }
  miniInfo.df90MortarTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688709/1EB7C549A90465F116EF307643FEA1D572CE1008/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702688820/94F2B4954FD378EA9E5544E37B80B8556812F2F2/",
      name = "DF-90 Mortar Trooper"
  }
  miniInfo.scoutTroopersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541911155/36E8C01A67E5E7A4188FC619261E0BAB0DF438C1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539603/6584D58DCD3135C901F302599C304E2D7044AD4B/",
      name = "Scout Trooper Leader"
  }
  miniInfo.scoutTroopers1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541911406/C33160A2888F0CE53C9712B1872478E038F9B0EA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539603/6584D58DCD3135C901F302599C304E2D7044AD4B/",
      name = "Scout Trooper"
  }
  miniInfo.scoutTroopers2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541911585/324AE8DA9D33C07E2FE620FC4B49E2C190F39F5A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539603/6584D58DCD3135C901F302599C304E2D7044AD4B/",
      name = "Scout Trooper"
  }
  miniInfo.scoutTroopers3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541911689/42647324CBDBF25155498DF1FFDDDC2EC04FB5EC/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539603/6584D58DCD3135C901F302599C304E2D7044AD4B/",
      name = "Scout Trooper"
  }
  miniInfo.dlt19xSniper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/770610077943667377/92306C3BFB675310563691C3C582BF5B9FC9ACD4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770610077943667167/66F3188269E49FE5DAD649E771D799F2593263FF/",
      name = "DLT-19x Sniper"
  }
  miniInfo.dlt19xSniperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/770610077943667377/92306C3BFB675310563691C3C582BF5B9FC9ACD4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770610077943667167/66F3188269E49FE5DAD649E771D799F2593263FF/",
      name = "DLT-19x Sniper",
      leader = true
  }
  miniInfo.sonicChargeSaboteur = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/950714557093539716/6A0D63306F505A074395AFA61EB990280DB8995D/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539899/FF7A535E91BF79D4C3E0D55E874C1ACEB6FBF434/",
      name = "Sonic Charge Saboteur"
  }
  miniInfo.sonicChargeSaboteurLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/950714557093539716/6A0D63306F505A074395AFA61EB990280DB8995D/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/950714557093539899/FF7A535E91BF79D4C3E0D55E874C1ACEB6FBF434/",
      name = "Sonic Charge Saboteur",
      leader = true
  }
  miniInfo.imperialRoyalGuardsLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541911959/D583DF28D96DBDF2F1FE9FB6AAB25809774C46EF/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541912060/182C0DD6D66EC8DEF075135B872DE26364010E27/",
      name = "Imperial Royal Guard Leader"
  }
  miniInfo.imperialRoyalGuards1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541912172/73A36C525BC98DD1F4EC7953943FE5F660B0E9D8/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541912060/182C0DD6D66EC8DEF075135B872DE26364010E27/",
      name = "Imperial Royal Guard"
  }
  miniInfo.imperialRoyalGuards2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541912365/CB3109223BD5A017AA159066A3B17002B8892047/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541912060/182C0DD6D66EC8DEF075135B872DE26364010E27/",
      name = "Imperial Royal Guard"
  }
  miniInfo.electrostaffGuard = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540541912278/DC9D78CD5742236F9F272AC1F8AA1D59D07CF5A9/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540541912060/182C0DD6D66EC8DEF075135B872DE26364010E27/",
      name = "Electrostaff Guard"
  }
  miniInfo.imperialDeathTroopersLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305474570/777B8146B150032E3D733D17110BE5887D1AB991/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305474695/F076E77D0278B10EAE330BC9073B05BC9A3BCD57/",
      name = "Imperial Death Troopers Leader"
  }
  miniInfo.imperialDeathTroopers1= {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305474824/49EFFD221EF1EBD3F3365B6B73B9A4A5C6E6A075/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305474695/F076E77D0278B10EAE330BC9073B05BC9A3BCD57/",
      name = "Imperial Death Troopers"
  }
  miniInfo.imperialDeathTroopers2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305474956/BB78111128E91BB2DB22F2990AFB438B9EA5FC0E/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305474695/F076E77D0278B10EAE330BC9073B05BC9A3BCD57/",
      name = "Imperial Death Troopers"
  }
  miniInfo.imperialDeathTroopers3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/951848302305475069/81803116C6F5F9B133D2D0CC39E2A2CA6043E9DB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305474695/F076E77D0278B10EAE330BC9073B05BC9A3BCD57/",
      name = "Imperial Death Troopers"
  }
  miniInfo.dtf16 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/993513208355174615/DD0DA9DFDBCA621CF297C9A9EB2356279A733158/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/951848302305474695/F076E77D0278B10EAE330BC9073B05BC9A3BCD57/",
      name = "DT-F16",
      leader = true
  }
  miniInfo.dlt19DTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/770610077943650040/CDB9EFD9CB36DE0EB5AB78B22F2B334BDB1E6DFE/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770610077942938053/6187B2D6848EC35010DE6C3EEBB5DF6125D02D45/",
      name = "DLT-19D Trooper"
  }

  local isfMaterials = "http://cloud-3.steamusercontent.com/ugc/1618438238123043414/B7E9660E470DC070545782406C29F1E1356A5685/"
  miniInfo.isfLeader = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238122999812/779C9D69CA440F970DD0B7C6394A812732F9C588/",
    assetbundle_secondary = isfMaterials,
    name = "Imperial Special Forces Leader"
  }
  miniInfo.isfInferno = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238122999341/C1AEEE50112F060BA8E5CAFBC16F417A0EF7C3C0/",
    assetbundle_secondary = isfMaterials,
    name = "Inferno Squad"
  }
  miniInfo.isf1 = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238122996093/C79160007FD884C2B8737DCA888D61C955073141/",
    assetbundle_secondary = isfMaterials,
    name = "Imperial Special Forces"
  }
  miniInfo.isf2 = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238122996656/AAD706C50446522C98259A20C03E757C4F7B98B1/",
    assetbundle_secondary = isfMaterials,
    name = "Imperial Special Forces"
  }
  miniInfo.isf3 = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238122997115/F100B28E5DBF4A56FB22D3410270BEE4EF344FEF/",
    assetbundle_secondary = isfMaterials,
    name = "Imperial Special Forces"
  }
  miniInfo.isfT21 = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618438238123000906/C64EAD02CA22F8BFB59320925DAD7D89BA1E7AD6/",
    assetbundle_secondary = isfMaterials,
    name = "T-21 Special Forces Trooper"
  }
  miniInfo.delMeeko = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618437692581074585/1C74BEB92DC42D3585BFC1185A77DE14EC3249CA/",
    assetbundle_secondary = isfMaterials,
    name = "Del Meeko"
  }
  miniInfo.gideonHask = {
    type = "assetbundle",
    assetbundle = "http://cloud-3.steamusercontent.com/ugc/1618437692581075349/6265F81E1BAA090FFA813270A8E3126CF8AD6CC5/",
    assetbundle_secondary = isfMaterials,
    name = "Gideon Hask",
    leader = true
  }

  miniInfo.speederBikeLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540542045928/74630975D4992CA09BDDD88460874FB9E4095FC9/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540542045645/AF0264339BB7E1D09E74AF920E2FB693C3CA1592/",
      name = "74-Z Speeder Bike Leader"
  }
  miniInfo.speederBike = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540542045506/0E2EC344AA0AD37699FFEFD4E1BA86A4FD4CD48B/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540542045645/AF0264339BB7E1D09E74AF920E2FB693C3CA1592/",
      name = "74-Z Speeder Bike"
  }
  miniInfo.eWebHeavyBlasterTeam = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234540542046063/4018BD67779A3F2ACCFA92C35306880C2FC60188/",
      collider = _BASE_COLLIDERS.large,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234540542046257/D259CAB86BBC7A60FB09149229F33508C8DF4CE8/",
      name = "E-Web Heavy Blaster Team"
  }
  miniInfo.dewbackRider = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/786359682702688959/0FCB94B52F0C2DF6E3F296AB6980CEC158E3E496/",
      collider = _BASE_COLLIDERS.large,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/786359682702689114/727755B3BE824994C869F1C869D8B5A07A3CD284/",
      name = "Dewback Rider"
  }
  miniInfo.atst = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/999141806429351360/24C098E7B3D1708CDCFB9AEA4B2C445EF2DBAEE0/",
      collider = _BASE_COLLIDERS.huge,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1752434998239690716/C6578DAF9012605B1F44A907D1C28646E34A73CF/",
      name = "AT-ST"
  }
  miniInfo.tx225 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/770610077943664603/48F725F2C3EAAF7514813A42EE084CE2E7382909/",
      collider = _BASE_COLLIDERS.long,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/770610077942978328/35E12FB664BC3AE0A7AFCCAFF306AFC7481CE4D3/",
      name = "TX-225 GAVw Occupier"
  }
  -- SEPARATIST
  miniInfo.generalGrievous = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869167436/AAA2C61A17BB43F2673AF16D30BD0478B9AAAD2A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869167571/EF86CBDA5F361282AD077D61FA81ABF0FEE061A0/",
      name = "General Grievous"
  }
  miniInfo.countDooku = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849586543/25BD09F275C593DB6C794359A9C50F3188F4D804/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849586640/B0512CC73C982F94EB5FEAE1661CF4438DAD8879/",
      name = "Count Dooku"
  }
  miniInfo.cadBane = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1003681674396400482/F8900CFC9EF2309C9F54AE33AE5444B2B09DB1CD/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1003681674396400696/907F4310FEA7A7CD89EE64A1AF3A8CC77897CCAC/",
      name = "Cad Bane"
  }
  miniInfo.maul = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1647717402898544477/AC748B04B4363679177B27F514758C308A2A7E49/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1647717402898544863/C61437A96B0AB9BC3C226475A87C9BB248D2CA2A/",
    name = "Maul"
}

  miniInfo.b1BattleDroid1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869167061/48F42C02EDD970E6DE8E59B8601EF3E7F11C1742/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869166919/FE5AD3A71430C729735E3FF7023D9E546E12FEF1/",
      name = "B1 Battle Droid"
  }
  miniInfo.b1BattleDroid2 = miniInfo.b1BattleDroid1
  miniInfo.b1BattleDroid3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869167318/DBC7863706A08B96020D3BFBE7A0C2C5689B7B08/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869166919/FE5AD3A71430C729735E3FF7023D9E546E12FEF1/",
      name = "B1 Battle Droid"
  }
  miniInfo.b1BattleDroid4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869166660/36AF6887F11FC70FF6AB75D0434EA79952C9E882/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869166919/FE5AD3A71430C729735E3FF7023D9E546E12FEF1/",
      name = "B1 Battle Droid"
  }
  miniInfo.b1BattleDroid5 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869167194/9ADFFD9AD608CBE3E9F6F61AB416E699A4156109/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869166919/FE5AD3A71430C729735E3FF7023D9E546E12FEF1/",
      name = "B1 Battle Droid"
  }
  miniInfo.b1BattleDroidLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780869166347/AA861F86A0B74CF335533E425A6CBACB99395A09/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780869166529/263C2AB95B1743539EC2CBDE40B0A14B1F5E5693/",
      name = "B1 Battle Droid Leader",
      altModelInfo = miniInfo.b1BattleDroid4
  }
  miniInfo.b1BattleDroid6 = miniInfo.b1BattleDroid3
  miniInfo.e5CB1Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780871782781/4DCE4780DE1CCDFB2996C28200A26C3B0696DD5A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780871782881/ADC1DBC3987C84AF486F9CD0E19A0455F4C33291/",
      name = "E-5C B1 Trooper"
  }
  miniInfo.e60RB1Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785234780871782500/34D317CFE0BE32E4FFFB84567822CDF7AC4D4C98/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785234780871782620/9A9EA2B54691F42EA6D34762D33D523A836201B2/",
      name = "E-60R B1 Trooper"
  }
  miniInfo.b1SecurityDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102173467517125/1BEF7A7795DF3F6DB91B84C1C82D8FBB24BF574B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102173467517405/DC3A7F38CF3839B7C5F2FCCE85745041094ADA81/",
      name = "B1 Security Droid"
  }
  miniInfo.e5sB1Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/766102422959434489/60F05B7FC8544DFC640CB33DA55F19EB5F2CB55A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/766102422959428835/10D3F8862BDECE8C0D7A874CC000F25CD6232168/",
      name = "E-5s B1 Trooper"
  }
  miniInfo.oomSeriesBattleDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785018348/F0B0C50757F4043A6C9B8746A73F8EC4342CA7DA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/767228764785012711/4DF65424F7D5400F0DC8A4DE7A028B373143CE6E/",
      name = "OOM-Series Battle Droid",
      leader = true
  }
  miniInfo.radiationCannonB1Trooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785008444/482C29486FD00312B2C7848D26A82793BCDF7D7F/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/767228764784997566/39300970854603B1F1539C46D70CC21280E278FF/",
      name = "Radiation Cannon B1 Trooper"
  }
  miniInfo.b2SuperBattleDroidLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849586118/94F967F21EA7E390A200C4BDA5581D07DBB37AC2/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2 Battle Droid Leader"
  }
  miniInfo.b2SuperBattleDroid1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849586430/E5941CF7A3631E6D4A28832AE489A4340C96B0B9/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2 Battle Droid"
  }
  miniInfo.b2SuperBattleDroid2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849586226/9326AD8D3EC80CC53F4BF2D156014978DCD715D9/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2 Battle Droid"
  }
  miniInfo.b2SuperBattleDroid3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849586324/B5D59E535AFA2BF99FCA3C584E28FA500ADB89BD/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2 Battle Droid"
  }
  miniInfo.b2HATrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849585631/7FF051E2079AB28A4FB77CCC739BCEB42F4CCFAA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2-HA Trooper"
  }
  miniInfo.b2ACMTrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/775105953849585917/4D4047069796D1E0567BE9ABD836984FDF12E80E/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/775105953849585789/91A639AB9F57BE393683DA53212E395886307C52/",
      name = "B2-ACM Trooper"
  }
  miniInfo.tSeriesTacticalDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1022821664192681738/6062182D66F6F043E4DCF98FCD592CBD7ECDFF18/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1022821664192681931/11AB7637C0B8C60CB2E4BDC90F006B887A69DAF0/",
      name = "T-Series Tactical Droid"
  }
  miniInfo.tSeriesTacticalDroidLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035003801/6062182D66F6F043E4DCF98FCD592CBD7ECDFF18/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035004142/11AB7637C0B8C60CB2E4BDC90F006B887A69DAF0/",
      name = "T-Series Tactical Droid",
      leader = true
  }
  miniInfo.evSeriesMedicalDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035000354/6248E4CAF3E978154106E7095E6984DCE6677CCA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035001447/E6B6EC2DDAE8CEA46A1384161E789D76F8F296BA/",
      name = "EV-Series Medical Droid"
  }
  miniInfo.pkSeriesWorkerDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035005605/95FAACF9FF4F9B6AB1921E3FD8C896DC631069BF/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035006060/711173DA172C4BC50686BBBC9C0D8BA1764D3175/",
      name = "PK-Series Worker Droid"
  }
  miniInfo.viperReconDroid = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364034959851/4D7F0531A10AEA9421878B1535604FDF1EBAE8D1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364034974176/209AEB14BF56D899CB9220BDB0BAB98CE2BA90D4/",
      name = "Viper Recon Droid"
  }
  miniInfo.drk1SithProbeDroidLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1693877203566022298/DF3FC1CF550C49A2C2340F5291798615E1978116/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1693877203566022493/549FA81DA79A87D9134AF78B2D39417113C1C71C/",
      name = "DRK-1 Sith Probe Droid Leader",
      leader = true
  }
  miniInfo.drk1SithProbeDroid1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1693877203566022298/DF3FC1CF550C49A2C2340F5291798615E1978116/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1693877203566022493/549FA81DA79A87D9134AF78B2D39417113C1C71C/",
      name = "DRK-1 Sith Probe Droid"
  }
  miniInfo.drk1SithProbeDroid2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1693877203566022298/DF3FC1CF550C49A2C2340F5291798615E1978116/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1693877203566022493/549FA81DA79A87D9134AF78B2D39417113C1C71C/",
      name = "DRK-1 Sith Probe Droid"
  }
  local bxDroidMaterials = "http://cloud-3.steamusercontent.com/ugc/773995528924546789/8774CBBDC3C4F18B11A444CC96EA5FE7F00DB48F/"
  miniInfo.bxCommandoDroidLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457847081/F7D4E8D3EC85BAEEB5C1B5B913B7F484CC28FC10/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid Leader"
  }
  miniInfo.bxCommandoDroid1 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457845802/AE70766EAA85C875B023FB980A5A5CEEFB98B1D9/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid"
  }
  miniInfo.bxCommandoDroid2 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457846188/D7F348E890430AA319DDDFA513D99DC2783ECF91/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid"
  }
  miniInfo.bxCommandoDroid3 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457846574/F169D9E2E45B73D1E21B17E32D3B4B4D9AACB196/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid"
  }
  miniInfo.bxCommandoDroidSniper = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457847963/0EA6BE014DA494689FF32F9570C6A73CD88F1894/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid Sniper"
  }
  miniInfo.bxCommandoDroidSniperLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457847963/0EA6BE014DA494689FF32F9570C6A73CD88F1894/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid Sniper",
      leader = true
  }
  miniInfo.bxCommandoDroidSaboteur = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457847567/079157D001A1520085C6A30620750817C6C01BFF/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid Saboteur"
  }
  miniInfo.bxCommandoDroidSaboteurLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457847567/079157D001A1520085C6A30620750817C6C01BFF/",
      assetbundle_secondary = bxDroidMaterials,
      name = "BX Commando Droid Saboteur",
      leader = true
  }
  miniInfo.droidekaLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785235151812759044/95037BEC00715812E918EC16919526DADE6F523F/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785235151812759497/47C2BFAE32E13C07FE68522008085B8C1F2EFDBD/",
      name = "Droideka Leader"
  }
  miniInfo.droideka1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785235151812759044/95037BEC00715812E918EC16919526DADE6F523F/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785235151812759310/88CC976372EF6B912EF2A761563F5632595C2295/",
      name = "Droideka"
  }
  miniInfo.STAPLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1003681674396285422/B2205A5D8B8CC1718D0C9B507BC3E33BCA815567/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1003681674396285744/5725FD4B443FFC2C6ADD751A4094D4B65944C098/",
      name = "STAP Rider Leader"
  }
  miniInfo.STAP1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1003681674396285422/B2205A5D8B8CC1718D0C9B507BC3E33BCA815567/",
      collider = _BASE_COLLIDERS.medium,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1003681674396285948/9C496D83F828E242C3C7CC18613FA83AD57BCF93/",
      name = "STAP Rider"
  }
  miniInfo.aatTank = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785235151813166538/2F32058DDD51C131547B66A3927041BDACDD9E72/",
      collider = _BASE_COLLIDERS.epic,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785235151813166725/2751E83472B0B6BD0559F5E77FAA3D62A0E17BB1/",
      name = "AAT Trade Federation Battle Tank"
  }

  -- REPUBLIC
  miniInfo.obiWanKenobi = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873394134/94407058FBA842AD0FDCC0BBB8AB613EA9A739C2/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873394267/272C1C9A8C15C36DC5C10DD62D5EFCEF9BFF4496/",
      name = "Obi-Wan Kenobi"
  }
  miniInfo.cloneCaptainRex = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/776232727456806720/869654FC3B0590BFFF2E1845C3CFA9169838EBF9/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/776232727456806858/52327997163A5113DF9E11B85F9DA8B6B970012C/",
      name = "Clone Captain Rex"
  }
  miniInfo.anakinSkywalker = {
    mesh = "http://cloud-3.steamusercontent.com/ugc/1647717402898546429/B304222EB644FD345A672FA36A7C4F5DF5152C49/",
    collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1647717402898546712/394E72447FF020F1D95846D07120EE63FCD0435B/",
    name = "Anakin Skywalker"
  }
  miniInfo.cloneCommander = {
  mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035126931/4EAB6085C2D2D6C176B3C9847E2F1F228CEFE7BB/",
  collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035127510/89D5E03C721391A7CBC7930180396F3B14E5273F/",
  name = "Clone Commander"
  }
  miniInfo.cloneCommanderLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035126931/4EAB6085C2D2D6C176B3C9847E2F1F228CEFE7BB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035127510/89D5E03C721391A7CBC7930180396F3B14E5273F/",
      name = "Clone Commander",
      leader = true
      }
  miniInfo.padme = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1003681674396399543/F485B2E6C10CBC01661E393966F014E5A5DE8BF9/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1003681674396399785/16C4492225E9C885997F59A86B4C1C67050F4197/",
      name = "Padme Amidala"
  }

  miniInfo.phaseICloneTrooper1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873393589/6AF627688F36D2049C1307BCB67A755FB27D51C5/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Trooper"
  }
  miniInfo.phaseICloneTrooper2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873393727/8C4030EF9FEEB32E048567DC2EC38A1985E7C8C0/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Trooper"
  }
  miniInfo.phaseICloneTrooper3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873457225/6382F0EA6E2DB0BC65921C3F4E5C97A84B422187/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Trooper"
  }
  miniInfo.phaseICloneTrooper4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873394019/F7EDA9D80C35FADA3C000A88C8105823172123B8/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Trooper"
  }
  miniInfo.phaseICloneTrooperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873393043/33A6FEA07374DAC8EBB6CDD463B6C761DC765D03/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Trooper Leader",
      altModelInfo = miniInfo.phaseICloneTrooper4
  }
  miniInfo.z6PhaseITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873393876/DEDAF52B0D07E0F2A2BCB54DE9A56E4FA437A3E4/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Z-6 Phase I Clone Trooper"
  }
  miniInfo.dc15PhaseITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873393393/915E79CA7D72B0DA950656C69F104A7BB586C0E0/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "DC-15 Phase I Clone Trooper"
  }
  miniInfo.phaseICloneSpecialist = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785643001/070425BBB2F0D33E71693679EEB72FEF790FE2F6/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873393180/6359B491483DCD9B2641BA134DC4B92DE10E9D92/",
      name = "Phase I Clone Specialist"
  }
  miniInfo.phaseICloneCaptain = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785646423/F890985F1B31042E0BC10996930089A3A22BE5C5/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/767228764785647603/8F9ADBD1429C1AF247858C877548E15E5996F4A9/",
      name = "Phase I Clone Captain",
      leader = true
  }
  miniInfo.rps6PhaseITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785603568/BB31C6873BD81E6B5B6F6D41B907DA95421063F0/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/767228764785565294/2AA6ABC62F52DCD30C56D5DED210C35E7B4FD526/",
      name = "RPS-6 Phase I Trooper"
  }
  miniInfo.dp23PhaseITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/767228764785625549/5461468E09D086E4CF7E835AE69D6F4226690518/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/767228764785620873/E3B1226B0836CF579F16C490896D5E2DE95C31F5/",
      name = "DP-23 Phase I Trooper"
  }
  local phaseIITexture = "http://cloud-3.steamusercontent.com/ugc/1028455893321728189/3FB4241F32F35813B6A934FCD3030D3F3D5B7090/"
  miniInfo.phaseIICloneTrooperLeader = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321070793/294DC7F7A6BE9E31AB2823745854EF8C31D3281A/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Clone Trooper Leader"
  }
  miniInfo.phaseIICloneTrooper1 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321407636/9315381415E55B835F091392658CBFDED02249F3/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Clone Trooper"
  }
  miniInfo.phaseIICloneTrooper2 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321577529/3034903B0501BE08E398BCC7F0D735B308DA9377/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Clone Trooper"
  }
  miniInfo.phaseIICloneTrooper3 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321405998/BF99DA12AC60F2548F73F5D0D001419BFBFA5CB1/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Clone Trooper"
  }
  miniInfo.phaseIICloneTrooper4 = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321406830/59DC907FEFEF65FBAF245A3B31A4251026FC93AA/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Clone Trooper"
  }
  miniInfo.z6PhaseIITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321579074/D5F10426146B81D46F02B027B9C4CC875FA6DA00/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Z-6 Phase II Trooper"
  }
  miniInfo.mortarPhaseIITrooper = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1028455893321578281/CBFA560559FE81326342AD0B65D2349447F882EB/",
      collider = _BASE_COLLIDERS.small,
      diffuse = phaseIITexture,
      name = "Phase II Mortar Trooper"
  }
  miniInfo.cloneCommsTechnician = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035131182/F5BA58F09282727EFB8E38BA478970E44B983EED/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035131690/ED66D23D4467396F6858928E9FEE1DABB4F9B446/",
      name = "Clone Comms Technician"
  }
  miniInfo.cloneEngineer = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035133539/7AD5C8B323760EFE19570C8F8D0DDA994973F03B/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035133984/DF3D2C9C54EBD45F87B48DCE203019FDD5FAECD2/",
      name = "Clone Engineer"
  }
  miniInfo.cloneMedic = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1683750364035135224/49D60D4EE5794A206AF8F604A68F58979CFEBC42/",
      collider = _BASE_COLLIDERS.small,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1683750364035135810/BD84B4C5CAA84DDA6302739AD749CD29B1C39669/",
      name = "Clone Medic"
  }

  local arcMaterials = "http://cloud-3.steamusercontent.com/ugc/773995200348530664/5E248091F8CC37B1023257338D4947E4ADFE48AB/"
  miniInfo.arcTrooperLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457802621/01F605D855048F823A0ECA6C46D2A62B56C04124/",
      -- assetbundle = "http://cloud-3.steamusercontent.com/ugc/776248816758255676/F51F732336CFEF3DCF549C2B396CD201FECE6A4B/",
      assetbundle_secondary = arcMaterials,
      name = "ARC Trooper Leader"
  }
  miniInfo.arcTrooper1 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457799750/AE83DC038BA8AAF48678D07E1F9734D4A9944C1D/",
      assetbundle_secondary = arcMaterials,
      name = "ARC Trooper"
  }
  miniInfo.arcTrooper2 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457800134/88E2FEC812AD5E7B7570836120992252AC758BF8/",
      assetbundle_secondary = arcMaterials,
      name = "ARC Trooper"
  }
  miniInfo.arcTrooper3 = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457800538/06BBAAAAC7FB68DAA9351F12008475068A96BFFB/",
      assetbundle_secondary = arcMaterials,
      name = "ARC Trooper"
  }
  miniInfo.arcTrooperDC15x = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457800878/34EC84D7ECD99E073417866A9BEC4288E00F5359/",
      assetbundle_secondary = arcMaterials,
      name = "DC-15x ARC Trooper"
  }
  miniInfo.arcTrooperDC15xLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457800878/34EC84D7ECD99E073417866A9BEC4288E00F5359/",
      assetbundle_secondary = arcMaterials,
      name = "DC-15x ARC Trooper",
      leader = true
  }
  miniInfo.echo = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457801321/CED1CD80F307683E79B9A4ED87CECAED7C070EBF/",
      assetbundle_secondary = arcMaterials,
      name = "Echo"
  }
  miniInfo.echoLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457801321/CED1CD80F307683E79B9A4ED87CECAED7C070EBF/",
      assetbundle_secondary = arcMaterials,
      name = "Echo",
      leader = true
  }
  miniInfo.fives = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457802221/506D704E232C1BFD85F063A24EBF24C5914C2C40/",
      assetbundle_secondary = arcMaterials,
      name = "Fives"
  }
  miniInfo.fivesLeader = {
      type = "assetbundle",
      assetbundle = "http://cloud-3.steamusercontent.com/ugc/1009315641457802221/506D704E232C1BFD85F063A24EBF24C5914C2C40/",
      assetbundle_secondary = arcMaterials,
      name = "Fives",
      leader = true
  }
  miniInfo.barcSpeeder = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873394399/018F8CC63E0D90F58AADA6328DF1709D4D1DF796/",
      collider = _BASE_COLLIDERS.large,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873394534/3E2F0490BA5D1024741F5806A4921D0E0E79EA9F/",
      name = "BARC Speeder"
  }
  miniInfo.republicATRT = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/1002556126520812865/51DA6EC33B5B7DC2274B97867C4E68F302AF5AE5/",
      collider = _BASE_COLLIDERS.large,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/1003681674396366135/D383D40E0AA3F75A159827B6938D2A93C75BC54B/",
      name = "Republic AT-RT"
  }
  miniInfo.saberTank = {
      mesh = "http://cloud-3.steamusercontent.com/ugc/785236717873392482/BC01571E47E96306C31FABABE3EA971814E00C96/",
      collider = _BASE_COLLIDERS.epic,
      diffuse = "http://cloud-3.steamusercontent.com/ugc/785236717873392638/CE1C3404249840D5F7F9499D1427E83530ACEB19/",
      name = "TX-130 Saber-Class Fighter Tank"
  }
  return miniInfo
end
