function translatePos(originPos, originRot, distance, angle)
  local pos = originPos
  local rot = originRot

  local a = distance * math.cos(math.rad(angle + rot.y))
  local b = distance * math.sin(math.rad(angle + rot.y))

  pos.x = pos.x - b
  pos.z = pos.z - a

  return pos
end

function simpleTranslatePos(originPos, xOffset, zOffset)
    local pos = {originPos.x + xOffset, originPos.y, originPos.z + zOffset}
    return pos
end